source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'
inhibit_all_warnings!

xcodeproj 'LGPlaceholderViewDemo'

target 'LGPlaceholderViewDemo' do
    pod 'LGPlaceholderView', :path => '../'
end
